UMT/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('', include('movtra.urls')),
	#path('movtra/', include('movtra.urls')),
    path('admin/', admin.site.urls),
]

movtra/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'movtra'
urlpatterns = [
	path('', views.index, name='index'),
	path('all', views.all, name='all'),
	path('upcoming', views.upcoming, name='upcoming'),
	path('nowplaying', views.nowplaying, name='nowplaying'),
	path('stats', views.stats, name='stats'),
	path('movie/<int:tmdbID>/', views.detail, name='detail'),
	path('movie/<int:tmdbID>/removeDiaryEntry/<int:diaryID>', views.removeDiaryEntry, name='removeDiaryEntry'),
	path('person/<int:tmdbID>/', views.personDetail, name='personDetail'),
	path('movie/<int:tmdbID>/editReview', views.editReview, name='editReview'),
	path('movie/<int:tmdbID>/saveReview', views.saveReview, name='saveReview'),
	path('lists/', views.lists, name='lists'),
	path('lists/editLists/', views.editLists, name='editLists'),

	url(r'^removeListsGET/$', views.removeListsGET, name='removeListsGET'),

	path('lists/<int:id>', views.listDetail, name='listDetail'),
	path('lists/<int:id>/editList', views.editList, name='editList'),
	path('lists/<int:id>/importList', views.importList, name='importList'),
	path('lists/<int:id>/addToList', views.addToList, name='addToList'),

	url(r'^removeMovieFromListGET/$', views.removeMovieFromListGET, name='removeMovieFromListGET'),

	path('movie/<int:tmdbID>/updateData', views.updateData, name='updateData'),

	path('lists/<int:id>/addToList/addMovieToList', views.addMovieToList, name='addMovieToList'),
	path('lists/newList', views.newList, name='newList'),
	url(r'^logMovie', views.logMovie, name='logMovie'),
	path('search', views.search, name='search'),
	path('results/<str:query>/<int:page>', views.results, name='results'),

]

movtra/forms.py
from django import forms

from .models import Movie

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    sender = forms.EmailField()
    cc_myself = forms.BooleanField(required=False)

class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=50)
    file = forms.FileField()

movtra/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from .models import Movie, List, isIn, Genres, isGenre, WorkedAsCast, WorkedAsCrew, Company, Produce, Country, ProductionCountry, Language, SpokenLanguage, LogEntry
from .utils import tmdb_api_wrap
import pprint
import csv
import codecs
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.core import serializers
from django.db import IntegrityError
import json
from itertools import islice
from datetime import datetime
from datetime import timedelta
import random
import pycountry

# Create your views here.

def index(request):
    latest_movies_list = Movie.objects.raw("""  select movtra_movie.*, movtra_logentry.* 
                                                from movtra_movie join movtra_logentry on movtra_logentry.movie_id=movtra_movie.id 
                                                where movtra_logentry.date is not null 
                                                order by date desc;
                                            """)
    context = {'latest_movies_list': latest_movies_list, 'all': False}
    return render(request, 'movtra/index.html', context)

def all(request):
    latest_movies_list = Movie.objects.order_by('-last_updated')[:24]
    context = {'latest_movies_list': latest_movies_list, 'all': True}
    return render(request, 'movtra/index.html', context)

def upcoming(request):
    upcoming = tmdb_api_wrap.getUpcoming()
    context =  {'results': upcoming,
                 'type': 1 # type 1 upcoming/nowplaying
                }
    return render(request, 'movtra/results.html', context)

def nowplaying(request):
    nowplaying = tmdb_api_wrap.getNowPlaying()
    context = {'results': nowplaying,
                'type': 1 # type 1 upcoming/nowplaying
                }
    return render(request, 'movtra/results.html', context)

# Return the serialization of a Movie entry
def serialize_movie(movie_entry):
    movie = {}
    for attr,k in movie_entry.__dict__.items():
        movie[attr] = k
    return movie

# Movie detail view
def detail(request, tmdbID):
        local = False # db presence flag
        try:
            # Check if the movie is in the db
            movie = Movie.objects.get(id=tmdbID)
            movie_serialized = serialize_movie(movie)
            local = True
        except Movie.DoesNotExist:
            movie = None
        if movie is None: # If not present in the db, get the information
            movie = tmdb_api_wrap.getMovieByID(tmdbID)
            genres=movie['genres']
            directors = {}
            dID=0
            for p in movie['credits']['crew']:
               if p['job'] == 'Director':
                    directors[dID] = {'name': p['name'], 'id': p['id']}
                    dID+=1
    
            g = []
            for gen in genres:
                g.append(gen['name'])
            return render(request, 'movtra/detail.html', {'movie': movie, 'genres': genres, 'directors': directors, 'local': local})
        else: # Otherwise look if it's present in any list
            isin = isIn.objects.filter(movie=movie).order_by('list')
            lists = {}
            lID=0
            for l in isin:
                lists[lID] = {'id': l.list.id,
                          'name': l.list.name}
                lID+=1

            # Uniform the genres and directors
            isgenre = isGenre.objects.filter(movie=movie)
            genres = []
            for g in isgenre:
                genres.append(g.genre.name)
            mov = tmdb_api_wrap.getMovieByID(tmdbID)
            genres=mov['genres']
            
            directors = {}
            dID=0
            for p in mov['credits']['crew']:
               if p['job'] == 'Director':
                    directors[dID] = {'name': p['name'], 'id': p['id']}
                    dID+=1

            # Get diary entries
            diary_entries = LogEntry.objects.filter(movie=movie)
            diary = {}
            eID = 0
            for e in diary_entries:
                diary[eID] = {'id': e.id,
                              'date': e.date,
                              'rating': e.rating,
                              'review': e.review}
                eID+=1
            return render(request, 'movtra/detail.html', {'movie': movie, 'lists': lists, 'genres': genres, 'directors' : directors, 'diary': diary, 'local': local})

# Log Movie function (refactor)
def logMovie(request):
    if request.method == 'POST':	
        date = request.POST.get('bday')
        tmdbID = request.POST.get('tmdbID')
        rating = request.POST.get('rating')
        review = ""
        review = request.POST.get('review')
        data = {'tmdbID': tmdbID , 'date': date, 'rating': rating, 'review': review}
        
        try:
            mov = Movie.objects.get(id=tmdbID)
        except Movie.DoesNotExist:
            mov = None
        if mov is None:
            addMovie(tmdbID)
        LogEntry.addLogEntry(data)
    return redirect(request.META['HTTP_REFERER'])

def search(request):
    query = ''
    if request.method == 'POST':
            query = request.POST.get('searchTitle')
    return redirect("/results/"+query+"/1")

def results(request, query, page):
    if page != '':
        page = page
    else:
        page = 1
    if request.method == 'POST':
            movieName = request.POST.get('searchTitle')
            if movieName == '':
                movieName = query
    else:
        movieName = query
    query = movieName

    if ' ' in movieName:
        movieName = movieName.replace(' ','+')
    results = tmdb_api_wrap.getMovieByName(movieName,page)
    total_pages = results[1]

    if page == total_pages:
        isNext = False
    else:
        isNext = True
    
    if page == 1:
        isBack = False
    else:
        isBack = True
    context = {'query': movieName ,'next_page': int(page)+1, 'isNext': isNext, 'back_page': int(page)-1 ,'isBack': isBack, 'page': page, 'results': results[0] , 'total_pages': total_pages, 'type': 0} #type 0 search
    return render(request, 'movtra/results.html', context)



# General purpose function to add a movie given its id to the dB
def addMovie(tmdbID):
    try:
        mov = Movie.objects.get(pk=tmdbID)
    except Movie.DoesNotExist:
        movie_data = tmdb_api_wrap.getMovieByID(tmdbID)
        try:
            Movie.addShow(movie_data)
            mov = Movie.objects.get(pk=tmdbID)
            
            for genre in movie_data['genres']:
                try:
                    genreID = Genres.objects.get(pk=genre['id'])
                    genreID = genre['id']
                except Genres.DoesNotExist:
                    genreID = Genres.addGenre(genre)
                isGenre.addGenreToMovie(tmdbID,genreID)
            
            for company in movie_data['production_companies']:
                try:
                    companyID = Company.objects.get(pk=company['id'])
                    companyID = company['id']
                except Company.DoesNotExist:
                    companyID = Company.addNewCompany(company)
                Produce.addProdutionCompany(tmdbID, companyID)

            for country in movie_data['production_countries']:
                try:
                    countryID = Country.objects.get(pk=country['iso_3166_1'])
                    countryID = country['iso_3166_1']
                except Country.DoesNotExist:
                    countryID = Country.addCountry(country)
                ProductionCountry.addProductionCountry(tmdbID, countryID)
            
            for language in movie_data['spoken_languages']:
                try:
                    languageID = Language.objects.get(pk=language['iso_639_1'])
                    languageID = language['iso_639_1']
                except Language.DoesNotExist:
                    languageID = Language.addLanguage(language)
                SpokenLanguage.addSpokenLanguage(tmdbID, languageID)
            
            # cast & crew
            credits = movie_data['credits']

            cast_objs = []
            batch_size = 0
            for personData in credits['cast']:
                try:
                    WorkedAsCast.objects.get(movie = mov, 
                                        cast_id = int(personData['cast_id']),
                                        character = personData['character'],
                                        credit_id = personData['credit_id'],
                                        gender = int(personData['gender']),
                                        person_id = str(personData['id']),        
                                        name = personData['name'],       
                                        order = int(personData['order']),
                                        profile_path = personData['profile_path'])
                except WorkedAsCast.DoesNotExist:
                    el = WorkedAsCast(movie = mov,
                                        cast_id = int(personData['cast_id']),
                                        character = personData['character'],
                                        credit_id = personData['credit_id'],
                                        gender = int(personData['gender']),
                                        person_id = str(personData['id']),        
                                        name = personData['name'],       
                                        order = int(personData['order']),
                                        profile_path = personData['profile_path'])
                    cast_objs.append(el)
                    batch_size +=1
                        
            # Manage the mySQL 999 varaibles limit
            while batch_size > 0:
                batch = list(islice(cast_objs, batch_size))
                
                if batch_size> 99:

movtra/templates/movtra.bak/detail.html
 {% extends 'movtra/layout.html' %}
{% block content %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}


<div class="row">
	<div class="col s4">
		<h3>{{ movie.title }} ({{movie.year}})</h>
		<h5>{{movie.tagline}}</h5>
		<!--<img src="https://image.tmdb.org/t/p/w600_and_h900_bestv2{{ movie.poster }}" height="50%" />-->
		<!-- <img src="{{ movie.photo.url }}" height="420"> -->

		{% load static %} 
		<!--<img src="{% static "/movtra/{{movie.title}}" %}"/> -->
		{% static "" as baseUrl %}
		<img src="{{ baseUrl }}movtra{{movie.poster}}" height="50%"></img>
		<p>Director: {{movie.director}}</p>
		<p>Runtime:  {{movie.runtime}}</p>
		<p>Genres: {{movie.genre|make_list|slice:':-2'|join:''}}</p>
	</div>
	<div class="col s6 ">
		<div class="valign-wrapper"><p>Overview: {{movie.overview}}</p></div>
		<fieldset class="rating">
					<input type="radio" id="star10" name="rating" value="10" /><label class = "full" for="star10" title="Awesome - 10 stars"></label>
					<input type="radio" id="star9" name="rating" value="9" /><label class="full" for="star9" title="Pretty good - 9 stars"></label>
					<input type="radio" id="star8" name="rating" value="8" /><label class = "full" for="star8" title="Pretty good - 8 stars"></label>
					<input type="radio" id="star7" name="rating" value="7" /><label class="full" for="star7" title="Meh - 7 stars"></label>
					<input type="radio" id="star6" name="rating" value="6" /><label class = "full" for="star6" title="Meh - 6 stars"></label>
					<input type="radio" id="star5" name="rating" value="5" /><label class="full" for="star5" title="Kinda bad - 5 stars"></label>
					<input type="radio" id="star4" name="rating" value="4" /><label class = "full" for="star4" title="Kinda bad - 4 stars"></label>
					<input type="radio" id="star3" name="rating" value="3" /><label class="full" for="star3" title="Meh - 3 stars"></label>
					<input type="radio" id="star2" name="rating" value="2" /><label class = "full" for="star2" title="Sucks big time - 2 star"></label>
					<input type="radio" id="star1" name="rating" value="1" /><label class="full checked" for="star1" title="Sucks big time - 1 stars"></label>
			</fieldset>
		<h3>Review:</h3>
		<form action="{% url 'movtra:editReview' movie.tmdbID %}" method="post">{% csrf_token %}
		<input type="submit" value="edit" name="edit">
		</form>
		<p>{{movie.review}}</p>
		{% if isIn %}
		<h4>Lists:</h4>
		<ul>
			{% for isin in isIn %}
			<li><a href="{% url 'movtra:listDetail' isin.list.id %}">{{isin.list.name}}</a></li>
			{% endfor %}
		</ul>
		{% else %}
		{% endif %}
	</div>
	<div class="col s2 center align-center">
		<div class="switch" >
			<form action="{% url 'movtra:seen' %}" method="post">{% csrf_token %}
				<p>
				<input type="hidden" name="seen" value="{{movie.tmdbID}}">
			Seen?: {% if movie.status_watched == True %} 
			<label>
				<input class="filled-in checkbox-orange" type="checkbox" value="{{movie.tmdbID}}" id="seen" onclick="this.form.submit();" checked><span class="lever"></label>
			{% else %}
			<label>
				<input  type="checkbox" value="{{movie.tmdbID}}" id="seen" onclick="this.form.submit();"><span class="lever"></label>
			{% endif %}
		</p>
			</form>
			<p>tmdb: {{movie.rating|make_list|slice:':-2'|join:''}}</p>
			<p>mine :{{movie.myRating|make_list|slice:':-2'|join:''}}</p>
		</div>
	</div>
</div>

<style>
@import url(//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css);

fieldset, label { margin: 0; padding: 0;}
/* Materialized edited*/
[type="radio"]:not(:checked)+label:before,[type="radio"]:not(:checked)+label:after {
 border:0px solid #5a5a5a
}
[type="radio"]+label:before,[type="radio"]+label:after {
 content:'';
 position:absolute;
 left:0;
 top:0;
 margin:4px;
 width:6px;
 display: none;
 height:16px;
 z-index:0;
 transition:.28s ease
}
[type="radio"]:checked+label:before {
 border:0px solid transparent
}



/****** Style Star Rating Widget *****/

.rating { 
  border: none;
  float: left;
}

.rating > input { display: none; } 
.rating > label:before { 
  margin: 5px;
  font-size: 1.25em;
  font-family: FontAwesome;
  display: inline-block;
  content: "\f005";
}

.rating > label { 
  color: #ddd; 
 float: right; 
}

/***** CSS Magic to Highlight Stars on Hover *****/

.rating > input:checked ~ label, /* show gold star when clicked */
.rating:not(:checked) > label:hover, /* hover current star */
.rating:not(:checked) > label:hover ~ label { color: #FFD700;  } /* hover previous stars in list */

.rating > input:checked + label:hover, /* hover current star when changing rating */
.rating > input:checked ~ label:hover,
.rating > label:hover ~ input:checked ~ label, /* lighten current selection */
.rating > input:checked ~ label:hover ~ label { color: #FFED85;  } 

.checked { 
	display: none;
	color: #FFD700;  }

</style>
{% endblock %}

movtra/templates/movtra.bak/editReview.html
{% extends 'movtra/layout.html' %}
{% block content %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}


<div class="row">
	<div class="col s4">
		<h3>{{ movie.title }} ({{movie.year}})</h>
		<h5>{{movie.tagline}}</h5>
		<!--<img src="https://image.tmdb.org/t/p/w600_and_h900_bestv2{{ movie.poster }}" height="50%" />-->
		<!-- <img src="{{ movie.photo.url }}" height="420"> -->

		{% load static %} 
		<!--<img src="{% static "/movtra/{{movie.title}}" %}"/> -->
		{% static "" as baseUrl %}
		<img src="{{ baseUrl }}movtra{{movie.poster}}" height="50%"></img>
		<p>Director: {{movie.director}}</p>
		<p>Runtime:  {{movie.runtime}}</p>
		<p>Genres: {{movie.genre|make_list|slice:':-2'|join:''}}</p>
	</div>
	<div class="col s6 ">
		<div class="valign-wrapper"><p>Overview: {{movie.overview}}</p></div>
		<h3>Review:</h3>
		<form action="{% url 'movtra:saveReview' movie.tmdbID %}" method="post">{% csrf_token %}
        <input type="submit" value="save" name="save">
        <textarea rows="50" cols="50" name="text">{{movie.review}}</textarea>
		</form>
		
		{% if isIn %}
		<h4>Lists:</h4>
		<ul>
			{% for isin in isIn %}
			<li><a href="{% url 'movtra:listDetail' isin.list.id %}">{{isin.list.name}}</a></li>
			{% endfor %}
		</ul>
		{% else %}
		{% endif %}
	</div>
	<div class="col s2 center align-center">
		<div class="switch" >
			<form action="{% url 'movtra:seen' %}" method="post">{% csrf_token %}
				<p>
				<input type="hidden" name="seen" value="{{movie.tmdbID}}">
			Seen?: {% if movie.status_watched == True %} 
			<label>
				<input class="filled-in checkbox-orange" type="checkbox" value="{{movie.tmdbID}}" id="seen" onclick="this.form.submit();" checked><span class="lever"></label>
			{% else %}
			<label>
				<input  type="checkbox" value="{{movie.tmdbID}}" id="seen" onclick="this.form.submit();"><span class="lever"></label>
			{% endif %}
		</p>
			</form>
			<p>tmdb: {{movie.rating|make_list|slice:':-2'|join:''}}</p>
			<p>mine :{{movie.myRating|make_list|slice:':-2'|join:''}}</p>
		</div>
	</div>
</div>
<style type="text/css">
textarea {
  height: 300px;
}
</style>
{% endblock %}

movtra/templates/movtra.bak/index.html
{% extends 'movtra/layout.html' %}

{% block content %}
	{% if latest_movies_list %}
	<div class="row">	
		{% for movie in latest_movies_list %}
    <div class="col s2">
      <div class="card {% if movie.status_watched %} green {% else %} red {%endif%}">
        <div class="card-image">
          <!--<img src="https://image.tmdb.org/t/p/w600_and_h900_bestv2{{ movie.poster }}" height="40%">-->
          {% load static %} 
          {% static "" as baseUrl %}
          <img src="{{ baseUrl }}movtra{{movie.poster}}" height="40%">
          <span class="card-title">{{movie.year|make_list|slice:':25'|join:''}}</span>
        </div>
        <div class="card-content">
          <p>{{movie.title}}</p>
        </div>
        <div class="card-action">
          <a href="{% url 'movtra:detail' movie.tmdbID %}">MOVIE INFO</a>
        </div>
      </div>
    </div>
  
		{% endfor %}
		</div>
	{% else %}
		<p>No movies are available.</p>
	{% endif %}
{% endblock %}

movtra/templates/movtra.bak/listAdd.html
{% extends 'movtra/layout.html' %}

{% block content %}
<h1>Results</h1>

<div class="row">
		{% for movie in results %}

			<div class="col s2">
      <div class="card">
        <div class="card-image">
          <img src="https://image.tmdb.org/t/p/w600_and_h900_bestv2{{ movie.poster_path }}" height="40%">
          <span class="card-title">{{ movie.release_date|slice:"0:4" }}</span>
        </div>
        <div class="card-content">
          <p>{{movie.title}}</p>
        </div>
        <div class="card-action">
        	<form action="{% url 'movtra:addMovieToList' movie.id %}" method="post">
            {% csrf_token %}
            <input type="submit" name="listadd" value="add">
            <input type="hidden" name="listid" value="{{ list_id }}">

          </form>
          <!--<a href="{% url 'movtra:resDetail' movie.id %}">MOVIE INFO</a>-->
        </div>
      </div>
    </div>
		{% endfor %}
</div>
{% endblock %}

movtra/templates/movtra.bak/listDetail.html
{% extends 'movtra/layout.html' %}

{% block content %}
<h1 class="center">{{ list.name }}  ({{ watched }}/{{ total }})</h1>

<div class="row card-panel">
<form action="{% url 'movtra:addToList' list.id %}" method="post">
      {% csrf_token %}
      <div class="col s6">
<input type="text" name="listTitle">
</div>
<div class="col s3">
<button type="submit" vaule="Add Title" class="waves-effect waves-light btn">Add Title</button>
</div>
</form>
</div>

<form action="{% url 'movtra:importList' list.id %}" method="post">
            {% csrf_token %}
            <input type="submit" name="import" value="import">
          </form>
<!--
<div class="row">	
		{% for m in movies %}
    <div class="col s2">
      <div class="card {% if m.movie.status_watched %} green {% else %} red {% endif %}">
        <div class="card-image">
          <img src="https://image.tmdb.org/t/p/w600_and_h900_bestv2{{ m.movie.poster }}" height="40%">
          <span class="card-title">{{m.movie.year|make_list|slice:':25'|join:''}}</span>
        </div>
        <div class="card-content">
          <p>{{m.movie.title}}</p>
        </div>
        <div class="card-action">
          <a href="{% url 'movtra:detail' m.movie.tmdbID %}">MOVIE INFO</a>
        </div>
      </div>
    </div>
    {% endfor %}
-->
<table>
  <tr>
    <th>Title</th>
    <th>Seen?</th>
  </tr>
{% for m in movies %}
<tr>
  <td>{{forloop.counter}}: <a href="{% url 'movtra:detail' m.movie.tmdbID %}">{{m.movie.title}} ({{m.movie.year|make_list|slice:':25'|join:''}})</p></a></td>
  <td><div class="switch" >
    <form action="{% url 'movtra:seen' %}" method="post" id="seenForm">{% csrf_token %}
      <p>
      <input type="hidden" name="seen" value="{{m.movie.tmdbID}}">
    {% if m.movie.status_watched == True %} 
    <label>
      <input class="filled-in checkbox-orange" type="checkbox" value="{{m.movie.tmdbID}}" id="seen" onclick="this.form.submit();" checked><span class="lever"></span></label>
      <input type="hidden" id="seenBool" value="False">
    {% else %}
    <label>
      <input  type="checkbox" value="{{m.movie.tmdbID}}" id="seen" onclick="this.form.submit();"><span class="lever"></span></label>
      <input type="hidden" id="seenBool" value="True">
    {% endif %}
  </p>
    </form>
  </div>
  <div>
    <form action="{% url 'movtra:removeMovieFromList' m.id %}" method="post">{% csrf_token %}
    <input type="submit" name="remove" value="Remove">
    <input type="hidden" name="removeID" vale="{{m.id}}"></form>
</div>
</td>
</tr>
{% endfor %}

</table>

<script>
  // Submit post on submit
$('#seenForm').click( function(event){
    //event.preventDefault();
    console.log("form submitted!")  // sanity check
    var flag = $('#seenBool').val()
    var res = false;
    if(flag === 'True'){
      res = true;
    }
    //console.log($('#seenBool').val())
    create_post(res);
});
/*
$('#check').on('change', function() {
    var val = this.checked ? this.value : '';
    $('#show').html(val);
});
*/
// AJAX for posting
function create_post(val) {
    console.log("create post is working!") // sanity check
    console.log(val)
};
</script>
{% endblock %}

movtra/templates/movtra.bak/lists.html
{% extends 'movtra/layout.html' %}

{% block content %}
<h1>Lists</h1>
<div class="row card-panel">
<form action="{% url 'movtra:newList' %}" method="post">
      {% csrf_token %}
      <div class="col s6">
<input type="text" name="listTitle">
</div>
<div class="col s3">
<button type="submit" vaule="Create list" class="waves-effect waves-light btn">Create list</button>
</div>
</form>
</div>
<!--<a class="waves-effect waves-light btn" href="newList">New List</a>-->
<!--<ul>
{% for l in list %}
  <li><a href="{% url 'movtra:listDetail' l.id %}">{{l.name}}</li>
{% endfor %}
</ul>-->
<table>
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>
</tbody>
{% for l in list %}
  <tr>
    <td><a href="{% url 'movtra:listDetail' l.id %}">{{l.name}}</a></td>
    <td><form action="{% url 'movtra:removeList' %}" method="post">
            {% csrf_token %}
            <input type="submit" name="remove" value="remove">
            <input type="hidden" name="listid" value="{{ l.id }}">

          </form></td>
  </tr>
{% endfor %}
</tbody>
</table>
{% endblock %}

movtra/templates/movtra.bak/resDetail.html
{% extends 'movtra/layout.html' %}

{% block content %}
<div class="row">
	<div class="col s4">
<h3>{{ movie.title }} ({{ movie.year }})</h1>
	<img src="https://image.tmdb.org/t/p/w600_and_h900_bestv2{{ movie.poster }}" height="50%" />
	<p>Director: {{movie.director}}</p>
	<p>Runtime:  {{movie.runtime}}</p>
	<p>Generes: {{movie.genres|make_list|slice:':-2'|join:''}}</p>
</div>
<div class="col s8">
	<p>{{ movie.overview }}</p>
	<div class="switch" >
			
	

			<form action="{% url 'movtra:add' %}" method="post">{% csrf_token %}
<p>
			<input type="hidden" name="tmdbID" value="{{movie.tmdbID}}">
		Seen?: 
		<label>
			<input class="filled-in checkbox-orange" type="checkbox" id="add" name="add" checked><span class="lever" /></label>
		</p>
	</div>
	<input type="submit" value="Add" ></li>
	</form>
</div>
{% endblock %}

movtra/templates/movtra.bak/results.html
{% extends 'movtra/layout.html' %}

{% block content %}
{% if search %}
  <h1>Results</h1>
{% endif %}

<div class="row">
		{% for movie in results %}

			<div class="col s2">
      <div class="card">
        <div class="card-image">
          <img src="https://image.tmdb.org/t/p/w600_and_h900_bestv2{{ movie.poster_path }}" height="40%">
          <span class="card-title">{{ movie.release_date|slice:"0:4" }}</span>
        </div>
        <div class="card-content">
          <p>{{movie.title}}</p>
        </div>
        <div class="card-action">
          <a href="{% url 'movtra:resDetail' movie.id %}">MOVIE INFO</a>
        </div>
      </div>
    </div>
		{% endfor %}
</div>
{% endblock %}