UMT/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('', include('movtra.urls')),
	#path('movtra/', include('movtra.urls')),
    path('admin/', admin.site.urls),
]

movtra/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'movtra'
urlpatterns = [
	path('', views.index, name='index'),
	path('all', views.all, name='all'),
	path('upcoming', views.upcoming, name='upcoming'),
	path('nowplaying', views.nowplaying, name='nowplaying'),
	path('stats', views.stats, name='stats'),
	path('movie/<int:tmdbID>/', views.detail, name='detail'),
	path('movie/<int:tmdbID>/removeDiaryEntry/<int:diaryID>', views.removeDiaryEntry, name='removeDiaryEntry'),
	path('person/<int:tmdbID>/', views.personDetail, name='personDetail'),
	path('movie/<int:tmdbID>/editReview', views.editReview, name='editReview'),
	path('movie/<int:tmdbID>/saveReview', views.saveReview, name='saveReview'),
	path('lists/', views.lists, name='lists'),
	path('lists/editLists/', views.editLists, name='editLists'),

	url(r'^removeListsGET/$', views.removeListsGET, name='removeListsGET'),

	path('lists/<int:id>', views.listDetail, name='listDetail'),
	path('lists/<int:id>/editList', views.editList, name='editList'),
	path('lists/<int:id>/importList', views.importList, name='importList'),
	path('lists/<int:id>/addToList', views.addToList, name='addToList'),

	url(r'^removeMovieFromListGET/$', views.removeMovieFromListGET, name='removeMovieFromListGET'),

	path('movie/<int:tmdbID>/updateData', views.updateData, name='updateData'),

	path('lists/<int:id>/addToList/addMovieToList', views.addMovieToList, name='addMovieToList'),
	path('lists/newList', views.newList, name='newList'),
	url(r'^logMovie', views.logMovie, name='logMovie'),
	path('search', views.search, name='search'),
	path('results/<str:query>/<int:page>', views.results, name='results'),

]

movtra/forms.py
from django import forms

from .models import Movie

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    sender = forms.EmailField()
    cc_myself = forms.BooleanField(required=False)

class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=50)
    file = forms.FileField()

movtra/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from .models import Movie, List, isIn, Genres, isGenre, WorkedAsCast, WorkedAsCrew, Company, Produce, Country, ProductionCountry, Language, SpokenLanguage, LogEntry
from .utils import tmdb_api_wrap
import pprint
import csv
import codecs
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.core import serializers
from django.db import IntegrityError
import json
from itertools import islice
from datetime import datetime
from datetime import timedelta
import random
import pycountry

# Create your views here.

def index(request):
    latest_movies_list = Movie.objects.raw("""  select movtra_movie.*, movtra_logentry.* 
                                                from movtra_movie join movtra_logentry on movtra_logentry.movie_id=movtra_movie.id 
                                                where movtra_logentry.date is not null 
                                                order by date desc;
                                            """)
    context = {'latest_movies_list': latest_movies_list, 'all': False}
    return render(request, 'movtra/index.html', context)

def all(request):
    latest_movies_list = Movie.objects.order_by('-last_updated')[:24]
    context = {'latest_movies_list': latest_movies_list, 'all': True}
    return render(request, 'movtra/index.html', context)

def upcoming(request):
    upcoming = tmdb_api_wrap.getUpcoming()
    context =  {'results': upcoming,
                 'type': 1 # type 1 upcoming/nowplaying
                }
    return render(request, 'movtra/results.html', context)

def nowplaying(request):
    nowplaying = tmdb_api_wrap.getNowPlaying()
    context = {'results': nowplaying,
                'type': 1 # type 1 upcoming/nowplaying
                }
    return render(request, 'movtra/results.html', context)

# Return the serialization of a Movie entry
def serialize_movie(movie_entry):
    movie = {}
    for attr,k in movie_entry.__dict__.items():
        movie[attr] = k
    return movie

# Movie detail view
def detail(request, tmdbID):
        local = False # db presence flag
        try:
            # Check if the movie is in the db
            movie = Movie.objects.get(id=tmdbID)
            movie_serialized = serialize_movie(movie)
            local = True
        except Movie.DoesNotExist:
            movie = None
        if movie is None: # If not present in the db, get the information
            movie = tmdb_api_wrap.getMovieByID(tmdbID)
            genres=movie['genres']
            directors = {}
            dID=0
            for p in movie['credits']['crew']:
               if p['job'] == 'Director':
                    directors[dID] = {'name': p['name'], 'id': p['id']}
                    dID+=1
    
            g = []
            for gen in genres:
                g.append(gen['name'])
            return render(request, 'movtra/detail.html', {'movie': movie, 'genres': genres, 'directors': directors, 'local': local})
        else: # Otherwise look if it's present in any list
            isin = isIn.objects.filter(movie=movie).order_by('list')
            lists = {}
            lID=0
            for l in isin:
                lists[lID] = {'id': l.list.id,
                          'name': l.list.name}
                lID+=1

            # Uniform the genres and directors
            isgenre = isGenre.objects.filter(movie=movie)
            genres = []
            for g in isgenre:
                genres.append(g.genre.name)
            mov = tmdb_api_wrap.getMovieByID(tmdbID)
            genres=mov['genres']
            
            directors = {}
            dID=0
            for p in mov['credits']['crew']:
               if p['job'] == 'Director':
                    directors[dID] = {'name': p['name'], 'id': p['id']}
                    dID+=1

            # Get diary entries
            diary_entries = LogEntry.objects.filter(movie=movie)
            diary = {}
            eID = 0
            for e in diary_entries:
                diary[eID] = {'id': e.id,
                              'date': e.date,
                              'rating': e.rating,
                              'review': e.review}
                eID+=1
            return render(request, 'movtra/detail.html', {'movie': movie, 'lists': lists, 'genres': genres, 'directors' : directors, 'diary': diary, 'local': local})

# Log Movie function (refactor)
def logMovie(request):
    if request.method == 'POST':	
        date = request.POST.get('bday')
        tmdbID = request.POST.get('tmdbID')
        rating = request.POST.get('rating')
        review = ""
        review = request.POST.get('review')
        data = {'tmdbID': tmdbID , 'date': date, 'rating': rating, 'review': review}
        
        try:
            mov = Movie.objects.get(id=tmdbID)
        except Movie.DoesNotExist:
            mov = None
        if mov is None:
            addMovie(tmdbID)
        LogEntry.addLogEntry(data)
    return redirect(request.META['HTTP_REFERER'])

def search(request):
    query = ''
    if request.method == 'POST':
            query = request.POST.get('searchTitle')
    return redirect("/results/"+query+"/1")

def results(request, query, page):
    if page != '':
        page = page
    else:
        page = 1
    if request.method == 'POST':
            movieName = request.POST.get('searchTitle')
            if movieName == '':
                movieName = query
    else:
        movieName = query
    query = movieName

    if ' ' in movieName:
        movieName = movieName.replace(' ','+')
    results = tmdb_api_wrap.getMovieByName(movieName,page)
    total_pages = results[1]

    if page == total_pages:
        isNext = False
    else:
        isNext = True
    
    if page == 1:
        isBack = False
    else:
        isBack = True
    context = {'query': movieName ,'next_page': int(page)+1, 'isNext': isNext, 'back_page': int(page)-1 ,'isBack': isBack, 'page': page, 'results': results[0] , 'total_pages': total_pages, 'type': 0} #type 0 search
    return render(request, 'movtra/results.html', context)



# General purpose function to add a movie given its id to the dB
def addMovie(tmdbID):
    try:
        mov = Movie.objects.get(pk=tmdbID)
    except Movie.DoesNotExist:
        movie_data = tmdb_api_wrap.getMovieByID(tmdbID)
        try:
            Movie.addShow(movie_data)
            mov = Movie.objects.get(pk=tmdbID)
            
            for genre in movie_data['genres']:
                try:
                    genreID = Genres.objects.get(pk=genre['id'])
                    genreID = genre['id']
                except Genres.DoesNotExist:
                    genreID = Genres.addGenre(genre)
                isGenre.addGenreToMovie(tmdbID,genreID)
            
            for company in movie_data['production_companies']:
                try:
                    companyID = Company.objects.get(pk=company['id'])
                    companyID = company['id']
                except Company.DoesNotExist:
                    companyID = Company.addNewCompany(company)
                Produce.addProdutionCompany(tmdbID, companyID)

            for country in movie_data['production_countries']:
                try:
                    countryID = Country.objects.get(pk=country['iso_3166_1'])
                    countryID = country['iso_3166_1']
                except Country.DoesNotExist:
                    countryID = Country.addCountry(country)
                ProductionCountry.addProductionCountry(tmdbID, countryID)
            
            for language in movie_data['spoken_languages']:
                try:
                    languageID = Language.objects.get(pk=language['iso_639_1'])
                    languageID = language['iso_639_1']
                except Language.DoesNotExist:
                    languageID = Language.addLanguage(language)
                SpokenLanguage.addSpokenLanguage(tmdbID, languageID)
            
            # cast & crew
            credits = movie_data['credits']

            cast_objs = []
            batch_size = 0
            for personData in credits['cast']:
                try:
                    WorkedAsCast.objects.get(movie = mov, 
                                        cast_id = int(personData['cast_id']),
                                        character = personData['character'],
                                        credit_id = personData['credit_id'],
                                        gender = int(personData['gender']),
                                        person_id = str(personData['id']),        
                                        name = personData['name'],       
                                        order = int(personData['order']),
                                        profile_path = personData['profile_path'])
                except WorkedAsCast.DoesNotExist:
                    el = WorkedAsCast(movie = mov,
                                        cast_id = int(personData['cast_id']),
                                        character = personData['character'],
                                        credit_id = personData['credit_id'],
                                        gender = int(personData['gender']),
                                        person_id = str(personData['id']),        
                                        name = personData['name'],       
                                        order = int(personData['order']),
                                        profile_path = personData['profile_path'])
                    cast_objs.append(el)
                    batch_size +=1
                        
            # Manage the mySQL 999 varaibles limit
            while batch_size > 0:
                batch = list(islice(cast_objs, batch_size))
                
                if batch_size> 99:

movtra/templates/movtra/detail.html
 {% extends 'movtra/layout.html' %}
{% block content %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<div class="container">
	<div class="row">
		<div class="col-sm-3">
			<fieldset>
				<h5>{{movie.tagline}}</h5>
				<img src="https://image.tmdb.org/t/p/w300{{ movie.poster_path }}">
				
				{% if local %}
				<p>Director(s):
					{% for k, v in directors.items %}
						<a href="{% url 'movtra:personDetail' v.id %}">{{v.name}}</a>
					{% endfor %}
				</p>
				<p>Genres: 
					{% for genre in genres %}
						{{genre.name}}
					{% endfor %}</p>
				{% else %}
				<p>Director(s): 
						{% for k, v in directors.items %}
							<a href="{% url 'movtra:personDetail' v.id %}">{{v.name}}</a>
						{% endfor %}
					</p>
				<p>Genres: {%for g in genres%}{{g.name}} {% endfor%}</p>
				
				{% endif %}
				
				<p>Runtime:  {{movie.runtime}} min</p>
				
				<p>tmdb: {{movie.vote_average}} [{{movie.vote_count}}]</p>
				
				<p>Release date: {{movie.release_date}}</p>
				{% if local %}
				<div>
					<form action="{% url 'movtra:updateData' movie.id %}" method="post" class="pr-0">
						{% csrf_token %}
						<div>
						<input class="btn btn-secondary" type="submit" name="update_data" value="Update data">
						<input type="hidden" name="movieID" value="{{ list_id }}">
					</div>
					</form>
				</div>
				{% endif %}
			</fieldset>
		</div>

		<div class="col-sm-9">
			<div class="row mb-8">
				<h3>{{ movie.title }} ({{ movie.release_date|make_list|slice:':-6'|join:'' }})</h3>
			</div>
			<div class="row">
				<div class="col-sm-8">
					<p id="overview">{{movie.overview}}</p>
					<div id="composer" class="composer-content">
						<div id="composeheader">
							{{movie.title}} 	(<a onclick="myFunction()">X</a>)
						</div>
						<form action="{% url 'movtra:logMovie' %}" method="post">{% csrf_token %}
							<input type="hidden" name="tmdbID" value="{{movie.id}}">
							<div id="to">
								Date <input type="date" name="bday">
							</div>
							<div id="object">
								<p>Rating</p>
								<fieldset class="rating">
									<input type="radio" id="star5" name="rating" value="5" /><label class = "full" for="star5" title="Awesome - 5 stars"></label>
									<input type="radio" id="star4half" name="rating" value="4.5" /><label class="half" for="star4half" title="Pretty good - 4.5 stars"></label>
									<input type="radio" id="star4" name="rating" value="4" /><label class = "full" for="star4" title="Pretty good - 4 stars"></label>
									<input type="radio" id="star3half" name="rating" value="3.5" /><label class="half" for="star3half" title="Meh - 3.5 stars"></label>
									<input type="radio" id="star3" name="rating" value="3" /><label class = "full" for="star3" title="Meh - 3 stars"></label>
									<input type="radio" id="star2half" name="rating" value="2.5" /><label class="half" for="star2half" title="Kinda bad - 2.5 stars"></label>
									<input type="radio" id="star2" name="rating" value="2" /><label class = "full" for="star2" title="Kinda bad - 2 stars"></label>
									<input type="radio" id="star1half" name="rating" value="1.5" /><label class="half" for="star1half" title="Meh - 1.5 stars"></label>
									<input type="radio" id="star1" name="rating" value="1" /><label class = "full" for="star1" title="Sucks big time - 1 star"></label>
									<input type="radio" id="starhalf" name="rating" value="0.5" /><label class="half" for="starhalf" title="Sucks big time - 0.5 stars"></label>		
								</fieldset>
							</div>
							<div>
								<textarea rows="8" cols="50" name="review"></textarea>
							</div>
							<div id="messageBody">
								<input type="submit" value="Log movie"> 
							</div>
						</form>
					</div>
					<fieldset>
							<h3>Diary:</h3>
							{% for k, entry in diary.items %}
							<p>{{forloop.counter}}) 
								{% if entry.date %}
									{{entry.date}}
								{% else %} 
									No date available 
								{% endif %} 
								| <i class="fa fa-star"></i> 
								{% if entry.rating %}
									{{entry.rating}}
								{% else %} 
									No rating available 
								{% endif %} 
								(<a href="{% url 'movtra:removeDiaryEntry' movie.id entry.id %}">delete</a>)
								(<a onclick="myFunction()">sa</a>)

							</p>
							{% if entry.review %}
							<p>↳{{entry.review}}</p>
							{% endif %}
							{% endfor %}
					</fieldset>
				</div>
				<div class="col-sm-2">
					<div class="row mb-4">
						<div class="composer">
							<button class="btn btn-primary" onclick="myFunction()" class="dropbtn">Log this movie</button>
						</div>
					</div>
					{% if lists %}
					<div class="row">
						<h4>Lists:</h4>
					</div>
					<div class="row">
						<ul>
							{% for k,v in lists.items %}
							<li><a href="{% url 'movtra:listDetail' v.id %}">{{v.name}}</a></li>
							{% endfor %}
						</ul>
					</div>
					{% else %}
					{% endif %}
				</div>
			</div>	
		</div>
	</div>
</div>

<style>
@import url(//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css);


img{
	height: 300px;
}
/*
#overview{
	margin-top: 100px;
}*/
/*
.input-group{
	position: absolute;
}
*/


@import url(//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css);

/*.rating, label { margin: 0; padding: 0; }

h1 { font-size: 1.5em; margin: 10px; }

/****** Style Star Rating Widget *****/

.rating { 
  border: none;
  float: left;
}

.rating > input { display: none; } 
.rating > label:before { 
  margin: 5px;
  font-size: 1.25em;
  font-family: FontAwesome;
  display: inline-block;
  content: "\f005";
}

.rating > .half:before { 
  content: "\f089";
  position: absolute;
}

.rating > label { 
  color: #ddd; 
 float: right; 
}

.composer-content > fieldset, label { margin: 0; padding: 0; }
/***** CSS Magic to Highlight Stars on Hover *****/

.rating > input:checked ~ label, /* show gold star when clicked */
.rating:not(:checked) > label:hover, /* hover current star */
.rating:not(:checked) > label:hover ~ label { color: #FFD700;  } /* hover previous stars in list */

.rating > input:checked + label:hover, /* hover current star when changing rating */
.rating > input:checked ~ label:hover,
.rating > label:hover ~ input:checked ~ label, /* lighten current selection */
.rating > input:checked ~ label:hover ~ label { color: #FFED85;  } 



.composer-content{
  color: black;
  background-color: #a64dff;
}
.composer-content {
    display: none;
    position: absolute;
    min-width: 560px;
    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
    z-index: 1;
}

.show {display:block;}
</style>
<script>
	function updateTextInput(val) {
		$('#uu').text(val)
		$('#subrating').submit();
        }
		function myFunction() {
document.getElementById("composer").classList.toggle("show");
}
</script>
{% endblock %}

movtra/templates/movtra/editList.html
{% extends 'movtra/layout.html' %}

{% block content %}
<h1 class="text-center">Editing {{ list.name }}  ({{ watched }}/{{ total }})</h1>

<div class="row ml-0 mr-0">
    <div class="col-sm-4">
    <form action="{% url 'movtra:addToList' list.id %}" method="post">
      {% csrf_token %}
      <div class="input-group mb-3 pl-4">
      <input type="text" class="form-control" name="listTitle">
      <div class="input-group-append">
      <button type="submit" vaule="Add Title" class="input-group-text">Add Title</button>
    </div>
    </div>
    </form>
  </div>
  <form action="{% url 'movtra:importList' list.id %}" method="post" class="pl-4">
    {% csrf_token %}
    <input type="submit" name="import" value="import" class="btn btn-secondary">
  </form>
  <form action="{% url 'movtra:listDetail' list.id %}" method="post" class="pl-2">
      {% csrf_token %}
      <input type="submit" name="edit" value="edit" class="btn btn-secondary">
  </form>
</div>

<div class="conatiner">
  <div class="list-group list-group-flush">
    {% for k, v in movies.items %}
    <div class="list-group-item d-flex flex-row bd-highlight">
      <div id="movie{{v.id}}">
        {{forloop.counter}}: 
        [<a class="removeBTN" id="movie{{v.id}}" href="#" data-movid="{{v.id}}" data-listid="{{list.id}}">X</a>]
        <a href="{% url 'movtra:detail' v.id %}">{{v.title}} ({{ v.year }})</a>
        {% if v.id in logentry %}
          watched
        {% endif %}
      </div>
    </div>
  {% endfor %}
  </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>

<script type="text/javascript">
  $('.removeBTN').on('click', function(e) {
    e.preventDefault();
    e.stopPropagation();
  var movid, listid;
  movid = $(this).attr("data-movid");
  listid = $(this).attr("data-listid");
  $.ajax(
  {
      type:"GET",
      url: "/removeMovieFromListGET",
      data:{
               movie_id: movid,
               list_id: listid
      },
      success: function( data ) 
      {
          $( '#movie'+ movid ).remove();
      }
   })
});
</script>

<script>
  // Submit post on submit
$('#seenForm').click( function(event){
    //event.preventDefault();
    console.log("form submitted!")  // sanity check
    var flag = $('#seenBool').val()
    var res = false;
    if(flag === 'True'){
      res = true;
    }
    //console.log($('#seenBool').val())
    create_post(res);
});
/*
$('#check').on('change', function() {
    var val = this.checked ? this.value : '';
    $('#show').html(val);
});
*/
// AJAX for posting
function create_post(val) {
    console.log("create post is working!") // sanity check
    console.log(val)
};
</script>
{% endblock %}

movtra/templates/movtra/listDetail.html
{% extends 'movtra/layout.html' %}

{% block content %}
<h1 class="text-center">{{ list.name }}  ({{ watched }}/{{ total }})</h1>

<div class="row ml-0 mr-0">
  <div class="col-sm-4">
    <form action="{% url 'movtra:addToList' list.id %}" method="post">
      {% csrf_token %}
      <div class="input-group mb-3 pl-4">
      <input type="text" class="form-control" name="listTitle">
      <div class="input-group-append">
      <button type="submit" vaule="Add Title" class="input-group-text">Add Title</button>
    </div>
    </div>
    </form>
  </div>
  <form action="{% url 'movtra:importList' list.id %}" method="post" class="pl-4">
    {% csrf_token %}
    <input type="submit" name="import" value="import" class="btn btn-secondary">
  </form>
  <form action="{% url 'movtra:editList' list.id %}" method="post" class="pl-2">
      {% csrf_token %}
      <input type="submit" name="edit" value="edit" class="btn btn-secondary">
  </form>
</div>



<div class="conatiner">
  <div class="list-group list-group-flush">
  {% for m in movies %}
    <div class="list-group-item d-flex flex-row bd-highlight">
      {{forloop.counter}}:&nbsp;
      <a href="{% url 'movtra:detail' m.movie.id %}">{{m.movie.title}} ({{ m.movie.release_date|make_list|slice:':-6'|join:'' }})</a> 
      {% if m.movie in logentry %}
        &nbsp;✓
      {% endif %}
      </p>
    </div>
  {% endfor %}

  </div>
</div>

<script>
  // Submit post on submit
$('#seenForm').click( function(event){
    //event.preventDefault();
    console.log("form submitted!")  // sanity check
    var flag = $('#seenBool').val()
    var res = false;
    if(flag === 'True'){
      res = true;
    }
    //console.log($('#seenBool').val())
    create_post(res);
});
/*
$('#check').on('change', function() {
    var val = this.checked ? this.value : '';
    $('#show').html(val);
});
*/
// AJAX for posting
function create_post(val) {
    console.log("create post is working!") // sanity check
    console.log(val)
};
</script>
{% endblock %}

movtra/templates/movtra/lists.html
{% extends 'movtra/layout.html' %}

{% block content %}
<h1>Lists</h1>
<div class="row ml-0 mr-0">
  <form action="{% url 'movtra:newList' %}" method="post">
    {% csrf_token %}
    <div class="input-group mb-3 pl-4">
      <input type="text" class="form-control" name="listTitle"/>
      <div class="input-group-append">
        <button  type="submit" vaule="Create list" class="input-group-text">Create list</button>
      </div>
    </div>
  </form>
    
  <form action="{% url 'movtra:editLists' %}" method="post" class="pl-4">
    {% csrf_token %}
    <input type="submit" name="edit" value="edit" class="btn btn-secondary">
</form>
</div>

<div class="conatiner">
    <div class="list-group list-group-flush">
    {% for l in list %}
    <div class="list-group-item d-flex flex-row bd-highlight"><a href="{% url 'movtra:listDetail' l.id %}">{{l.name}}</a></div>
    {% endfor %}
    </div>
</div>
<style>
  td {
    height: 20px;
  }
  
</style>
{% endblock %}

movtra/templates/movtra/listsEdit.html
{% extends 'movtra/layout.html' %}

{% block content %}
<h1>Lists</h1>
<div class="row ml-0 mr-0">
  <form action="{% url 'movtra:newList' %}" method="post">
    {% csrf_token %}
    <div class="input-group mb-3 pl-4">
      <input type="text" class="form-control" name="listTitle">
      <div class="input-group-append">
        <button type="submit" vaule="Create list" class="input-group-text">Create list</button>
      </div>
    </div>
  </form>

  <form action="/lists/" method="post" class="pl-4">
    {% csrf_token %}
    <input type="submit" name="edit" value="edit" class="btn btn-secondary">
</form>
</div>
<div class="continer">
  <div class="list-group list-group-flush">
      {% for l in list %}
      <div id="list{{l.id}}" class="list-group-item d-flex flex-row bd-highlight">
      <div class="p-2 bd-highlight" id="list{{l.id}}">[<a class="removeBTN" id="movie{{l.id}}" href="#" data-listid="{{l.id}}">X</a>] <a href="{% url 'movtra:listDetail' l.id %}">{{l.name}}</a></div>
      </div>
      {% endfor %}
    </ul>
  </div>
</div>
<style>
  td {
    height: 20px;
  }

</style>

<script type="text/javascript">
  $('.removeBTN').on('click', function(e) {
    e.preventDefault();
    e.stopPropagation();
  var movid, listid;
  listid = $(this).attr("data-listid");
  $.ajax(
  {
      type:"GET",
      url: "/removeListsGET",
      data:{
               "list_id": listid
      },
      success: function( data ) 
      { 
        $( '#list'+ listid ).remove();
      }
   });
  });

</script>
{% endblock %}

movtra/templates/movtra/results.html
{% extends 'movtra/layout.html' %}

{% block content %}
{% if type < 2  %}
  {% if type == 0  %}
    {% if total_pages == 0  %}
    <h1 class="text-center">No results for: "{{query}}"</h1>
    {% else %}
    <h1 class="text-center">Results for: "{{query}}"</h1>
    {% endif %}
  {% endif %}
<div class="container">
  <div class="list-group list-group-flush">
    {% for movie in results %}
    
        <div class="list-group-item d-flex flex-row bd-highlight">
           
            <div class="p-2 bd-highlight">
                
              <img  src="https://image.tmdb.org/t/p/w92{{ movie.poster_path }}">
            </a>
            </div>
            <div class="p-2 bd-highlight">
                <a href="{% url 'movtra:detail' movie.id %}">{{movie.title}}</a>
          </div>
        
        </div>
      
    {% endfor %}
  </div>
</div>
  {% if type == 0  %}
  {% if total_pages != 0  %}
    <div id="page-selector" class="d-flex justify-content-center">
      <span class="text-center">Page: {{page}} of {{ total_pages }}&nbsp;</span>  
      {% if isBack %}<a href="{% url 'movtra:results' query back_page %}">back&nbsp;</a>{% endif %}
      {% if isNext %}<a href="{% url 'movtra:results' query next_page %}">next</a>{% endif %}
    </div>
    {% endif %}
    {% endif %}
  </div>
 

    {% elif type == 2 %}

    <div class="container">
    <div class="col-sm">
        {% for movie in results %}
        <div class="row">
            <div class="col-sm-4">
                <img src="https://image.tmdb.org/t/p/w600_and_h900_bestv2{{ movie.poster_path }}">
           </div>
          <div class="col-sm-4">
              
            <a href="{% url 'movtra:detail' movie.id %}"> <p>{{movie.title}}</p></a>
          </div>
          <form action="{% url 'movtra:addMovieToList' movie.id %}" method="post">
            {% csrf_token %}
            <input type="submit" name="listadd" value="+">
            <input type="hidden" name="listid" value="{{ list_id }}">

          </form>
        </div>
        
        {% endfor %}
    </div>
  </div>
  <style>
    img{
      height: 20%;
    }
    .row{
      height: 20%;
    }
  
    </style>
    {% endif %}
{% endblock %}